/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare class Host {
  constructor(ip: string, port: number)
  get ipAddress(): string
  get port(): number
  setEmitter(emitter: (...args: any[]) => any): void
  service(): void
}
