/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Host {
  /**
   * Creates a new ENet host for communicating with peers.
   *
   * @param ip_address - The IP address to bind to
   * @param port - The port number to bind to
   * @param peer_limit - The maximum number of peers that should be allocated for the host
   * @param channel_limit - The maximum number of channels allowed (cannot be 0)
   * @param using_new_packet - Whether to use new packet format
   * @param using_new_packet_server - Whether server uses new packet format
   * @param incoming_bandwidth_limit - Downstream bandwidth limit in bytes/second, or null for no limit
   * @param outgoing_bandwidth_limit - Upstream bandwidth limit in bytes/second, or null for no limit
   * @param enable_compressor - Enable RangeCoder compression (defaults to true)
   * @param enable_checksum - Enable CRC32 checksum validation (defaults to true)
   * @param seed - Random number generator seed, or null for random seed
   */
  constructor(ipAddress: string, port: number, peerLimit: number, channelLimit: number, usingNewPacket: boolean, usingNewPacketServer: boolean, incomingBandwidthLimit?: number | undefined | null, outgoingBandwidthLimit?: number | undefined | null, enableCompressor?: boolean | undefined | null, enableChecksum?: boolean | undefined | null, seed?: number | undefined | null)
  /**
   * Get the IP address of the host socket.
   * @returns The IP address as a string
   */
  get ipAddress(): string
  /**
   * Get the port number of the host socket.
   * @returns The port number
   */
  get port(): number
  /**
   * Get the maximum number of peers that can connect to this host.
   * @returns The peer limit
   */
  get peerLimit(): number
  /**
   * Get the maximum allowed channels for future incoming connections.
   * @returns The channel limit
   */
  get channelLimit(): number
  /**
   * The maximum transmission unit (MTU), or the maximum packet size that will be sent by this host.
   * @returns The MTU value
   */
  get mtu(): number
  /**
   * Initiates a connection to a foreign host.
   * @param ip_address - The IP address of the remote host
   * @param port - The port number of the remote host
   * @returns True if connection initiated successfully, false otherwise
   */
  connect(ipAddress: string, port: number): boolean
  /**
   * Get a snapshot of peer data by peer ID.
   * Returns a NativePeer object containing current state and statistics.
   * @param net_id - The peer ID
   * @returns NativePeer snapshot containing peer data
   * @throws Error if peer not found
   */
  getPeer(netId: number): NativePeer
  /**
   * Checks for any queued events on the host.
   * @returns True if there are queued events, false otherwise
   */
  checkEvents(): boolean
  /**
   * Get the number of connected peers.
   * @returns The count of currently connected peers
   */
  peerCount(): number
  /**
   * Get the current time according to this host.
   * @returns Time in milliseconds since epoch
   */
  now(): number
  /**
   * Send a reliable packet to a specific peer.
   * @param net_id - The peer ID to send to
   * @param data - The packet data to send
   * @param channel_id - The channel ID to send on
   * @returns True if packet queued successfully
   * @throws Error if peer not found or send fails
   */
  send(netId: number, data: Buffer, channelId: number): boolean
  /**
   * Sends any queued packets on the host to its designated peers.
   * @returns True on success
   */
  flush(): boolean
  /**
   * Queues a packet to be sent to all connected peers.
   * @param data - The packet data to broadcast
   * @param channel_id - The channel ID to broadcast on
   * @returns True on success
   */
  broadcast(data: Buffer, channelId: number): boolean
  /**
   * Limits the maximum allowed channels of future incoming connections.
   * @param channel_limit - The channel limit (cannot be 0)
   * @returns True on success
   * @throws Error if channel_limit is 0
   */
  setChannelLimit(channelLimit: number): boolean
  /**
   * Adjusts the bandwidth limits of the host in bytes/second.
   * ENet will strategically drop packets to ensure bandwidth is not overwhelmed.
   * The bandwidth parameters also determine the window size which limits reliable packets in transit.
   * @param incoming - Downstream bandwidth limit in bytes/second, or null for no limit (cannot be 0)
   * @param outgoing - Upstream bandwidth limit in bytes/second, or null for no limit (cannot be 0)
   * @returns True on success
   * @throws Error if limits are set to 0
   */
  setBandwidthLimit(incoming?: number | undefined | null, outgoing?: number | undefined | null): boolean
  /**
   * Get the host's current bandwidth limits.
   * @returns Object with optional 'incoming' and 'outgoing' properties (bytes/second), undefined if no limit
   */
  getBandwidthLimit(): object
  /**
   * Set the maximum transmission unit (MTU) for this host.
   * @param mtu - The MTU value (must be between PROTOCOL_MINIMUM_MTU and PROTOCOL_MAXIMUM_MTU)
   * @returns True on success
   * @throws Error if MTU is out of valid range
   */
  setMtu(mtu: number): boolean
  /**
   * Set the event emitter callback function.
   * This callback will be invoked during service() calls when events occur.
   * @param emitter - The callback function to handle events (connect, raw, disconnect)
   */
  setEmitter(emitter: (...args: any[]) => any): void
  /**
   * Checks for events on the host and shuttles packets between the host and its peers.
   * Should be called regularly for adequate performance.
   * Dispatches events to the emitter callback set via set_emitter().
   * @throws Error if emitter is not set
   */
  service(): void
}
/**
 * A snapshot of peer data and statistics.
 * This struct contains a point-in-time copy of peer information.
 * To perform operations on the peer, use the methods which require a Host reference.
 */
export declare class NativePeer {
  /** The peer's network ID. */
  get netId(): number
  /** The peer's current state (as numeric value). */
  get state(): number
  /** Whether this peer is currently in a connected state. */
  get connected(): boolean
  /** The IP address of the peer. */
  get ip(): string
  /** The port number of the peer. */
  get port(): number
  /** Round trip time (RTT) in milliseconds. */
  get rtt(): number
  /** Mean round trip time (RTT) in milliseconds between sending a reliable packet and receiving its acknowledgement. */
  get roundTripTime(): number
  /** Round trip time (RTT) variance in milliseconds. */
  get roundTripTimeVariance(): number
  /** The maximum transmission unit (MTU) for this peer. */
  get mtu(): number
  /** Number of channels allocated for communication with this peer. */
  get channelCount(): number
  /** Downstream bandwidth of the peer in bytes/second. */
  get incomingBandwidth(): number
  /** Upstream bandwidth of the peer in bytes/second. */
  get outgoingBandwidth(): number
  /** Total amount of downstream data received from this peer. */
  get incomingDataTotal(): number
  /** Total amount of upstream data sent to this peer. */
  get outgoingDataTotal(): number
  /** Total number of packets sent to this peer. */
  get packetsSent(): number
  /** Total number of packets lost from this peer. */
  get packetsLost(): number
  /** Mean packet loss of reliable packets as a ratio. */
  get packetLoss(): number
  /** Variance of the mean packet loss. */
  get packetLossVariance(): number
  /** Ping interval in milliseconds. */
  get pingInterval(): number
  /** Timeout limit value. */
  get timeoutLimit(): number
  /** Minimum timeout value in milliseconds. */
  get timeoutMinimum(): number
  /** Maximum timeout value in milliseconds. */
  get timeoutMaximum(): number
  /** Last round trip time variance. */
  get lastRoundTripTimeVariance(): number
  /** Last round trip time. */
  get lastRoundTripTime(): number
  /** Lowest round trip time recorded. */
  get lowestRoundTripTime(): number
  /** Packet throttle interval. */
  get packetThrottleInterval(): number
  /** Packet throttle acceleration rate. */
  get packetThrottleAcceleration(): number
  /** Packet throttle deceleration rate. */
  get packetThrottleDeceleration(): number
  /** Current packet throttle value. */
  get packetThrottle(): number
  /** Incoming bandwidth throttle epoch. */
  get incomingBandwidthThrottleEpoch(): number
  /** Outgoing bandwidth throttle epoch. */
  get outgoingBandwidthThrottleEpoch(): number
  /**
   * Send a ping request to this peer.
   * Ping requests factor into the mean round trip time.
   * ENet automatically pings all connected peers at regular intervals,
   * however this function may be called to ensure more frequent ping requests.
   * @param host - The host instance managing this peer
   */
  ping(host: Host): void
  /**
   * Send a reliable packet to this peer on the specified channel.
   * @param host - The host instance managing this peer
   * @param channel_id - The channel ID to send on
   * @param data - The packet data to send
   * @returns True if packet queued successfully
   */
  send(host: Host, channelId: number, data: Buffer): boolean
  /**
   * Request a disconnection from this peer.
   * An Event::Disconnect will be generated once the disconnection is complete.
   * @param host - The host instance managing this peer
   * @param data - An integer value to pass to the peer upon disconnection
   * @returns True on success
   */
  disconnect(host: Host, data: number): boolean
  /**
   * Force an immediate disconnection from this peer.
   * No Event::Disconnect will be generated.
   * The foreign peer is not guaranteed to receive the disconnect notification.
   * @param host - The host instance managing this peer
   * @param data - An integer value to pass to the peer upon disconnection
   * @returns True on success
   */
  disconnectNow(host: Host, data: number): boolean
  /**
   * Request a disconnection from this peer, but only after all queued outgoing packets are sent.
   * An Event::Disconnect will be generated once the disconnection is complete.
   * @param host - The host instance managing this peer
   * @param data - An integer value to pass to the peer upon disconnection
   * @returns True on success
   */
  disconnectLater(host: Host, data: number): boolean
  /**
   * Forcefully disconnect this peer without notification.
   * The foreign host represented by this peer is not notified of the disconnection and will timeout.
   * @param host - The host instance managing this peer
   * @returns True on success
   */
  reset(host: Host): boolean
  /**
   * Set timeout parameters for this peer.
   * Timeout values use an exponential backoff mechanism.
   * If a reliable packet is not acknowledged within some multiple of the average RTT,
   * the timeout will be doubled until it reaches the limit.
   * @param host - The host instance managing this peer
   * @param limit - The timeout limit (defaults to PEER_TIMEOUT_LIMIT if 0)
   * @param minimum - The minimum timeout (defaults to PEER_TIMEOUT_MINIMUM if 0)
   * @param maximum - The maximum timeout (defaults to PEER_TIMEOUT_MAXIMUM if 0)
   * @returns True on success
   */
  setTimeout(host: Host, limit: number, minimum: number, maximum: number): boolean
  /**
   * Set the interval at which pings will be sent to this peer in milliseconds.
   * Pings are used to monitor connection liveness and dynamically adjust the throttle
   * during periods of low traffic for better responsiveness during traffic spikes.
   * @param host - The host instance managing this peer
   * @param ping_interval - The ping interval in milliseconds
   * @returns True on success
   */
  setPingInterval(host: Host, pingInterval: number): boolean
  /**
   * Configure throttle parameters for this peer.
   * The throttle represents a probability that an unreliable packet should be sent.
   * When throttle is at maximum, 100% of unreliable packets are sent.
   * When at 0, all unreliable packets are dropped.
   * @param host - The host instance managing this peer
   * @param interval - Interval in milliseconds over which to measure lowest mean RTT
   * @param acceleration - Rate at which to increase throttle probability as RTT declines
   * @param deceleration - Rate at which to decrease throttle probability as RTT increases
   * @returns True on success
   */
  setThrottle(host: Host, interval: number, acceleration: number, deceleration: number): boolean
  /**
   * Set the maximum transmission unit (MTU) for this peer.
   * @param host - The host instance managing this peer
   * @param mtu - The MTU value (must be between PROTOCOL_MINIMUM_MTU and PROTOCOL_MAXIMUM_MTU)
   * @returns True on success
   * @throws Error if MTU is out of valid range
   */
  setMtu(host: Host, mtu: number): boolean
}
